name: Sync
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run sync script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_QUERY: ${{ secrets.GH_QUERY }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          ASSIGNEES_TO_IGNORE: ${{ secrets.ASSIGNEES_TO_IGNORE }}
        run: make
